# Generated by Django 4.0 on 2022-01-29 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('krishibariapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='videoTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='video/%y')),
            ],
        ),
        migrations.RemoveField(
            model_name='dbtable',
            name='username',
        ),
        migrations.AddField(
            model_name='dbtable',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='dbtable',
            name='is_subAdmin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dbtable',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
