# Generated by Django 4.0 on 2022-02-27 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('krishibariapp', '0004_courseslist_active_state_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='allArticles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('article', models.TextField()),
                ('auther', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='krishibariapp.dbtable')),
            ],
        ),
    ]
