# Generated by Django 4.0 on 2022-02-28 18:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('krishibariapp', '0005_allarticles'),
    ]

    operations = [
        migrations.CreateModel(
            name='articleComment',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.TextField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='krishibariapp.articlecomment')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='krishibariapp.allarticles')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='krishibariapp.dbtable')),
            ],
        ),
    ]
