# Generated by Django 4.0 on 2022-02-28 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('krishibariapp', '0006_articlecomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlecomment',
            name='parent',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='krishibariapp.articlecomment'),
        ),
        migrations.AlterField(
            model_name='articlecomment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='krishibariapp.allarticles'),
        ),
    ]
