# Generated by Django 4.0 on 2022-03-18 13:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krishibariapp', '0010_allblogs'),
    ]

    operations = [
        migrations.AddField(
            model_name='allblogs',
            name='likes',
            field=models.ManyToManyField(related_name='blogpost_like', to=settings.AUTH_USER_MODEL),
        ),
    ]
