# Generated by Django 4.0 on 2022-03-22 06:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krishibariapp', '0014_alter_allblogs_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='allblogs',
            name='bookmark',
            field=models.ManyToManyField(blank=True, null=True, related_name='bookmark', to=settings.AUTH_USER_MODEL),
        ),
    ]
