# Generated by Django 4.0 on 2022-04-01 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('krishibariapp', '0018_allquestion_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allquestion',
            old_name='created',
            new_name='timestamp',
        ),
    ]
