# Generated by Django 4.0 on 2022-04-01 17:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('krishibariapp', '0019_rename_created_allquestion_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allquestion',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
