# Generated by Django 4.0 on 2022-04-03 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krishibariapp', '0020_alter_allquestion_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='allquestion',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
