# Generated by Django 4.0 on 2022-04-06 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krishibariapp', '0023_alter_courseslist_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseslist',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
