# Generated by Django 4.0 on 2022-05-18 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('krishibariapp', '0026_courseslist_instructor_dbtable_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allcoursevideos',
            name='caption',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='allcoursevideos',
            name='name',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='krishibariapp.courseslist'),
        ),
        migrations.AlterField(
            model_name='allcoursevideos',
            name='video',
            field=models.FileField(blank=True, upload_to='video/%y'),
        ),
        migrations.AlterField(
            model_name='courseslist',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='krishibariapp.dbtable'),
        ),
        migrations.CreateModel(
            name='courseStudents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='krishibariapp.courseslist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='krishibariapp.dbtable')),
            ],
        ),
    ]
