# Generated by Django 4.0 on 2022-05-23 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krishibariapp', '0028_rename_user_coursestudents_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursestudents',
            name='transection_id',
            field=models.TextField(max_length=30, null=True),
        ),
    ]
