# Generated by Django 4.0 on 2022-06-12 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('krishibariapp', '0031_course_exam_answer_correct_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_exam',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'easy'), ('medium', 'medium'), ('hard', 'hard')], max_length=6),
        ),
        migrations.AlterField(
            model_name='courseslist',
            name='about',
            field=models.CharField(blank=True, max_length=1000000, null=True),
        ),
        migrations.AlterField(
            model_name='courseslist',
            name='course_name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.CreateModel(
            name='liveCourseList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.CharField(blank=True, max_length=1000000, null=True)),
                ('live_course_name', models.CharField(max_length=255, unique=True)),
                ('image', models.ImageField(default='images/default.jpg', upload_to='images/')),
                ('videoSessionLink', models.URLField(blank=True, null=True)),
                ('active_state', models.BooleanField(default=False)),
                ('instructor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='krishibariapp.dbtable')),
            ],
        ),
    ]
