# Generated by Django 4.0 on 2022-06-13 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krishibariapp', '0033_rename_courseslist_onlinecourselist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='livecourselist',
            name='course_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='course_exam',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'easy'), ('medium', 'medium'), ('hard', 'hard')], max_length=6),
        ),
    ]
