# Generated by Django 4.0 on 2022-06-13 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krishibariapp', '0034_livecourselist_course_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='livecourselist',
            name='course_overview',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='livecourselist',
            name='course_overview_image',
            field=models.ImageField(default='images/default.jpg', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='livecourselist',
            name='learning_objectives',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='livecourselist',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='onlinecourselist',
            name='course_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='onlinecourselist',
            name='course_overview',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='onlinecourselist',
            name='course_overview_image',
            field=models.ImageField(default='images/default.jpg', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='onlinecourselist',
            name='learning_objectives',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='onlinecourselist',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
