# Generated by Django 4.0 on 2022-06-13 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krishibariapp', '0035_livecourselist_course_overview_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livecourselist',
            name='active_state',
        ),
        migrations.AlterField(
            model_name='course_exam',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'easy'), ('hard', 'hard'), ('medium', 'medium')], max_length=6),
        ),
    ]
