# Generated by Django 4.0 on 2022-06-14 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krishibariapp', '0036_remove_livecourselist_active_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='allblogs',
            name='blog_image',
            field=models.ImageField(default='images/default.jpg', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='allblogs',
            name='blog_overview',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='course_exam',
            name='difficulty',
            field=models.CharField(choices=[('medium', 'medium'), ('easy', 'easy'), ('hard', 'hard')], max_length=6),
        ),
    ]
