# Generated by Django 4.0 on 2022-06-20 09:22

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('krishibariapp', '0037_allblogs_blog_image_allblogs_blog_overview_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='question_answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', ckeditor.fields.RichTextField()),
                ('timestamp', models.DateField(default=django.utils.timezone.now)),
                ('auther', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='krishibariapp.dbtable')),
                ('dislike', models.ManyToManyField(blank=True, null=True, related_name='answer_dislike', to=settings.AUTH_USER_MODEL)),
                ('like', models.ManyToManyField(blank=True, null=True, related_name='answer_like', to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='krishibariapp.allquestion')),
            ],
        ),
    ]
