# Generated by Django 4.0 on 2022-06-20 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krishibariapp', '0039_alter_course_exam_difficulty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_exam',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'easy'), ('hard', 'hard'), ('medium', 'medium')], max_length=6),
        ),
    ]
