# Generated by Django 4.0 on 2022-06-20 12:01

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krishibariapp', '0040_alter_course_exam_difficulty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allarticles',
            name='article',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='allblogs',
            name='the_blog',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='allquestion',
            name='question',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course_exam',
            name='difficulty',
            field=models.CharField(choices=[('medium', 'medium'), ('easy', 'easy'), ('hard', 'hard')], max_length=6),
        ),
        migrations.AlterField(
            model_name='question_answer',
            name='answer',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
