# Generated by Django 4.0 on 2022-06-22 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krishibariapp', '0041_alter_allarticles_article_alter_allblogs_the_blog_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_exam',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'easy'), ('hard', 'hard'), ('medium', 'medium')], max_length=6),
        ),
        migrations.AlterField(
            model_name='dbtable',
            name='profile_pic',
            field=models.ImageField(default='images/profile-icon.png', upload_to='images/'),
        ),
    ]
